### ISSUE TITLE
PointCut a method in a jar

### ISSUE THREAD

**Issue by alokright** [jdvp/AndroidAspectExample#1]
I am unable to pointcut a method from a jar. Code compiles but Advice is never called

**Comment by jdvp** [comment]
@alokright This project isn't affiliated with the android-gradle-aspectj plugin. You might take a look at their GitHub for some documentation of that plugin directly:
https://github.com/Archinamon/android-gradle-aspectj

I suspect that you need to use the includeJar directive

**Comment by alokright** [comment]
Thanks.

**Comment by alokright** [comment]
I am stuck with the jar weaving issue. Please take a look at this [demo](https://github.com/alokright/AspectJ-Jar-Demo/blob/main/app/src/main/java/com/free/demo/TestAspects.java) and share some pointers.
Thanks for your help.

**Comment by jdvp** [comment]
I tried fixing your project.
With the version you are using (4.2.1) there is a bug that seems to make includeJar behave incorrectly:
https://github.com/Archinamon/android-gradle-aspectj/issues/122

However, I was able to get it working with the following configuration:
Gradle 6.5
Android Gradle Plugin 4.1.1
AspectJ Plugin 4.3.0

Futher, your includeJar declaration should be updated:
```
aspectj {
    includeJar "mediationsdk"
}
```

After making those changes, I was able to see the aspects in the build/ajc-transform.log file and also in logcat as you are firing a Log event for each advice:
<img width="955" alt="Screen Shot 2020-12-09 at 10 12 29 AM" src="https://user-images.githubusercontent.com/7111196/101648086-778f6380-3a07-11eb-8b4e-e860faf85754.png">


Hope this helps @alokright

**Comment by alokright** [comment]
Thank you very much
