### ISSUE TITLE
What's the proper proguard rules for release version of Aspect project?

### ISSUE THREAD

**Issue by deverhjj** [jdvp/AndroidAspectExample#4]
The aspectj does work on AGP8+, but the advice method can't receive the annotation of the Pointcut with AGP 8.0+, I guess because of obfuscate code, but it works on AGP 7.x.x. I don't know how to add extra proguard rules for aspectj project.
Is there anyone know the reason? Thanks.

    @Aspect
    public class SingleClickAspect {
        private long mStartTime = 0;

        private SingleClickAspect() {
        }

        @Pointcut("execution(@com.example.aspectjdemo.SingleClick * *(..)) && @annotation(metaData)")
        public void method(SingleClick metaData) {
        }

       @Around("method(metaData)")
       public Object singleClickAdvice(ProceedingJoinPoint joinPoint, SingleClick metaData)
            throws Throwable {
            Log.e("SingleClickAspect", "metaData=" + metaData); // metaData is null when running on released apk.
       }
    }

**Comment by jdvp** [comment]
@deverhjj Hadn't seen that before but TBH I don't really use AspectJ anymore. Did you check to see if anything in the README helped? For example if you are updating Kotlin at the same time it may cause issues as well unless extra compiler options are added
